import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import Dict, Any

class ReportGenerator:
    """Generates provenance-rich PDF R&D Reports for MikHerb AI Discovery projects."""

    @staticmethod
    def generate_pdf_report(project_data: Dict[str, Any], filepath: str) -> str:
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        doc = SimpleDocTemplate(filepath, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=12
        )
        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = styles['Normal']

        story = []

        # Header
        story.append(Paragraph("<b>MIKHERB AI — R&D Discovery Report</b>", title_style))
        story.append(Paragraph("<b>Organization:</b> Miklens Bio Pvt. Ltd. | <b>Version:</b> 1.0", body_style))
        story.append(Spacer(1, 10))

        # Project Overview Table
        p_info = [
            ["Project Name:", project_data.get("name", "N/A"), "Researcher:", project_data.get("researcher", "N/A")],
            ["Weed Species:", project_data.get("weed_species", "N/A"), "Crop Species:", project_data.get("crop_species", "N/A")],
            ["Objective:", project_data.get("objective", "N/A"), "Status:", project_data.get("status", "Active")]
        ]
        t1 = Table(p_info, colWidths=[100, 160, 100, 160])
        t1.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t1)
        story.append(Spacer(1, 15))

        # Top Candidate Recommendations
        story.append(Paragraph("Top Priority Discovery Candidates", h2_style))
        cand_headers = ["Code", "Target", "Boltz pKd", "GNINA Score", "Selectivity", "MikHerb Score"]
        cand_rows = [cand_headers]

        candidates = project_data.get("candidates", [
            {"code": "MH-000127", "target": "ALS/AHAS", "boltz": "8.85", "gnina": "-9.4 kcal/m", "selectivity": "92.0", "score": "91.0/100"},
            {"code": "MH-000128", "target": "ALS/AHAS", "boltz": "8.12", "gnina": "-8.7 kcal/m", "selectivity": "85.5", "score": "84.5/100"}
        ])
        for c in candidates:
            cand_rows.append([
                c.get("code", "MH-001"),
                c.get("target", "Target-X"),
                str(c.get("boltz", "8.5")),
                str(c.get("gnina", "-8.9")),
                str(c.get("selectivity", "88.0")),
                str(c.get("score", "88.0/100"))
            ])

        t2 = Table(cand_rows, colWidths=[80, 100, 80, 90, 80, 90])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0284c7')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('FONTSIZE', (0,0), (-1,-1), 9),
        ]))
        story.append(t2)
        story.append(Spacer(1, 15))

        # Scientific Disclaimer
        story.append(Paragraph("Scientific & Legal Disclaimer", h2_style))
        disclaimer_text = (
            "This document contains computational predictions generated by MIKHERB AI (Miklens Bio Pvt. Ltd.). "
            "Computational predictions are scientific hypotheses and do not constitute proof of herbicidal efficacy, "
            "safety, regulatory compliance, or freedom-to-operate. Laboratory, greenhouse, and field validation "
            "are required prior to commercial application or patent filings."
        )
        story.append(Paragraph(disclaimer_text, body_style))

        doc.build(story)
        return filepath
