import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import Dict, Any

class ReportGenerator:
    """Generates provenance-rich PDF R&D Reports for MikHerb AI Discovery projects without hardcoded fallback metrics."""

    @staticmethod
    def generate_pdf_report(project_data: Dict[str, Any], filepath: str) -> str:
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        doc = SimpleDocTemplate(filepath, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=20,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=12
        )
        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = styles['Normal']

        story = []

        story.append(Paragraph("<b>MIKHERB AI — R&D Discovery Report</b>", title_style))
        story.append(Paragraph("<b>Organization:</b> Miklens Bio Pvt. Ltd. | <b>Version:</b> 1.0", body_style))
        story.append(Spacer(1, 10))

        p_info = [
            ["Project Name:", project_data.get("name", "N/A"), "Researcher:", project_data.get("researcher", "N/A")],
            ["Weed Species:", project_data.get("weed_species", "N/A"), "Crop Species:", project_data.get("crop_species", "N/A")],
            ["Objective:", project_data.get("objective", "N/A"), "Status:", project_data.get("status", "Active")]
        ]
        t1 = Table(p_info, colWidths=[100, 160, 100, 160])
        t1.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t1)
        story.append(Spacer(1, 15))

        story.append(Paragraph("Top Priority Discovery Candidates", h2_style))
        cand_headers = ["Code", "Target", "Boltz pKd", "GNINA Score", "Selectivity", "MikHerb Score"]
        cand_rows = [cand_headers]

        candidates = project_data.get("candidates", [])
        if candidates:
            for c in candidates:
                cand_rows.append([
                    str(c.get("code", "N/A")),
                    str(c.get("target", "N/A")),
                    str(c.get("boltz", "NOT_INSTALLED")),
                    str(c.get("gnina", "NOT_INSTALLED")),
                    str(c.get("selectivity", "N/A")),
                    str(c.get("score", "N/A"))
                ])
        else:
            cand_rows.append(["N/A", "N/A", "N/A", "N/A", "N/A", "NO_CANDIDATE_DATA"])

        t2 = Table(cand_rows, colWidths=[80, 100, 80, 90, 80, 90])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0284c7')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('FONTSIZE', (0,0), (-1,-1), 9),
        ]))
        story.append(t2)
        story.append(Spacer(1, 15))

        story.append(Paragraph("Scientific & Legal Disclaimer", h2_style))
        disclaimer_text = (
            "This document contains computational predictions generated by MIKHERB AI (Miklens Bio Pvt. Ltd.). "
            "Computational predictions are scientific hypotheses and do not constitute proof of herbicidal efficacy, "
            "safety, regulatory compliance, or freedom-to-operate. Laboratory, greenhouse, and field validation "
            "are required prior to commercial application or patent filings."
        )
        story.append(Paragraph(disclaimer_text, body_style))

        doc.build(story)
        return filepath
